version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"


# postgres://username:password@localhost:5432/database_name
# export DATABASE_DSN=postgres://admin:1234@localhost:5432/test_db

  /
  yandex-go